
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-2, 2560x1440@144, 0x0, 1
monitor = HDMI-A-1, 1920x1080, -1920x300, 1

workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1

$mainMod = SUPER # Sets "Windows" key as main modifier
bind = $mainMod SHIFT, p, movewindow, mon:+1
